-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 02, 2024 lúc 11:28 AM
-- Phiên bản máy phục vụ: 10.4.32-MariaDB
-- Phiên bản PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `product_details`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `san_pham`
--

CREATE TABLE `san_pham` (
  `id` int(5) NOT NULL,
  `ten_san_pham` varchar(255) NOT NULL,
  `gia` int(9) NOT NULL,
  `img` varchar(255) DEFAULT NULL,
  `danh_muc` varchar(50) DEFAULT NULL,
  `quy_cach` text DEFAULT NULL,
  `nha_san_xuat` varchar(60) DEFAULT NULL,
  `nuoc_san_xuat` varchar(15) DEFAULT NULL,
  `thanh_phan` text DEFAULT NULL,
  `cong_dung` text DEFAULT NULL,
  `doi_tuong_su_dung` text DEFAULT NULL,
  `cach_su_dung` text DEFAULT NULL,
  `thoi_han_su_dung` varchar(20) DEFAULT NULL,
  `bao_quan` text DEFAULT NULL,
  `luu_y_khi_su_dung` text DEFAULT NULL,
  `so_dang_ky` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_vietnamese_ci;

--
-- Đang đổ dữ liệu cho bảng `san_pham`
--

INSERT INTO `san_pham` (`id`, `ten_san_pham`, `gia`, `img`, `danh_muc`, `quy_cach`, `nha_san_xuat`, `nuoc_san_xuat`, `thanh_phan`, `cong_dung`, `doi_tuong_su_dung`, `cach_su_dung`, `thoi_han_su_dung`, `bao_quan`, `luu_y_khi_su_dung`, `so_dang_ky`) VALUES
(1, 'Viên uống Golex Ocavill hỗ trợ chống lại sự phình to của tuyến tiền liệt, cải thiện các rối loạn tiểu tiện (30 viên)', 495000, 'https://github.com/Lizard943/webshop/blob/master/img/1.png?raw=true', 'Thận, tiền liệt tuyến', 'Hộp 30 Viên', 'THE OXFORD HEALTH COMPANY LTD', 'Anh', 'Chiết xuất Cây cọ lùn (Saw Palmetto), Hạt bí ngô, Tầm ma, Kẽm, Lycopene, Vitamin E, Vitamin B6', 'Golex hỗ trợ chống lại sự phình to của tuyến tiền liệt, cải thiện các rối loạn tiểu tiện ở bệnh nhân phì đại tiền liệt tuyến: Tiểu đêm, tiểu buốt, tiểu không hết, tiểu nhiều lần. Hạn chế sự phát triển của u xơ tiền liệt tuyến lành tính hoặc sử dụng để hỗ trợ sau phẫu thuật.', 'Golex dùng trong các trường hợp: Nam giới ở tuổi trung và cao niên, có các triệu chứng như rối loạn tiểu tiện như: Tiểu đêm, tiểu buốt, tiểu rắt, tiểu không hết, tiểu nhiều lần, tia nước tiểu yếu... Nam giới bị u xơ tiền liệt tuyến lành tính hoặc sử dụng để hỗ trợ sau phẫu thuật.', 'Uống 2 viên mỗi ngày, uống sau bữa ăn.', '24 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng. Để xa tầm tay trẻ em.', 'Không dùng cho người mẫn cảm với bất kỳ thành phần nào của sản phẩm. Người đang dùng thuốc, phụ nữ mang thai hoặc cho con bú, hỏi ý kiến thầy thuốc trước khi dùng. Thực phẩm bảo vệ sức khỏe, không thể thay thế chế độ ăn uống đa dạng và cân bằng. Không dùng cho người dưới 18 tuổi.', '9471/2023/ĐKSP'),
(2, 'Viên nhai Borne Mineral New Nordic hỗ trợ phát triển xương, giúp tăng chiều cao, tăng đề kháng (120 viên)', 635000, 'https://github.com/Lizard943/webshop/blob/master/img/2.jpg', 'Cơ xương khớp', 'Hộp 120 Viên', 'LEGOSAN AB', 'Thụy Điển', 'Canxi, Magie, Vitamin D3', 'Borne Mineral hỗ trợ sự phát triển của xương giúp tăng trưởng chiều cao, giảm nguy cơ còi xương thấp bé, phòng ngừa thiếu canxi ở trẻ em và hỗ trợ tăng cường sức đề kháng.', 'Borne Mineral dùng trong các trường hợp sau: Trẻ em từ 3 tuổi trở lên. Trẻ bị thiếu canxi. Còi xương. Chậm lớn. Trẻ ở tuổi dậy thì cần tăng chiều cao.', 'Nhai 2 viên mỗi ngày.', '18 tháng kể từ ngày ', 'Đậy kín sản phẩm, bảo quản nơi khô ráo, thoáng mát, tránh ánh sáng trực tiếp. Để xa tầm tay trẻ em.', 'Không dùng cho người mẫn cảm với bất kỳ thành phần nào của sản phẩm. Phụ nữ có thai và cho con bú, trẻ em dưới 3 tuổi phải tham khảo ý kiến của chuyên gia chăm sóc sức khỏe trước khi sử dụng. Không dùng cho người tiểu đường. Không dùng cho người tăng canxi huyết. Không dùng quá liều khuyến cáo. Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh. Đọc kỹ hướng dẫn sử dụng trước khi dùng.', '6120/2023/ĐKSP'),
(3, 'Thực phẩm bảo vệ sức khỏe Calcium Premium JpanWell bổ sung canxi, giảm nguy cơ loãng xương (120 viên)', 920000, 'https://github.com/Lizard943/webshop/blob/master/img/3.jpg', 'Cơ xương khớp', 'Hộp 120 Viên', 'Have fun Factory Co., Ltd', 'Nhật Bản', 'Canxi từ vỏ sò, Chất xơ hòa tan, Vi khuẩn acid lactic, Magie, Sắt, Vitamin B2, Vitamin B1, Vitamin D3, Vitamin K2', 'Thực phẩm bảo vệ sức khỏe Calcium Premium bổ sung canxi, một số các vitamin (vitamin B1, vitamin B2, vitamin D3, vitamin K2) và khoáng chất (magie, sắt) cho cơ thể; hỗ trợ tăng khả năng hấp thụ canxi; hỗ trợ giảm nguy cơ loãng xương.', 'Thực phẩm bảo vệ sức khỏe Calcium Premium thích hợp dùng cho người trưởng thành.', 'Uống 2 - 4 viên/ngày với nước nguội hoặc nước ấm.', '3 năm kể từ ngày sản', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng. Để xa tầm tay trẻ em.', 'Người đang điều trị bệnh, người đang dùng các loại thuốc, phụ nữ mang thai, phụ nữ cho con bú vui lòng tham khảo ý kiến chuyên gia trước khi sử dụng. Không sử dụng cho người mẫn cảm, kiêng kị với bất kỳ thành phần nào của sản phẩm. Không sử dụng cho đối tượng tăng canxi huyết, canxi niệu.', '6734/2023/ĐKSP'),
(4, 'Viên uống Rama Bổ Phổi hỗ trợ bổ phổi, giảm ho (30 viên)', 132000, 'https://github.com/Lizard943/webshop/blob/master/img/4.jpg', 'Hô hấp, ho, xoang', 'Hộp 30 Viên', 'CÔNG TY TNHH CÔNG NGHỆ HERBITECH', 'Việt Nam', 'Cao hỗn hợp thảo mộc, Chiết xuất Mạch môn, chiết xuất cúc tím, Chiết xuất gừng, Chiết xuất xuyên tâm liên, Chiết xuất Trần bì, Chiết xuất Huyết giác, Chiết xuất Đông trùng hạ thảo, Vitamin C, Fucoidan 80%', 'Rama Bổ Phổi hỗ trợ bổ phổi, hỗ trợ giảm ho, giảm đờm, giảm đau rát họng, khản tiếng do viêm họng, viêm phế quản.', 'Rama Bổ Phổi thích hợp dùng cho trẻ em từ 6 tuổi trở lên và người lớn bị ho, ho có đờm, đau rát họng, khản tiếng do viêm họng, viêm phế quản.', 'Trẻ 6 - 12 tuổi: Uống 1 viên/lần x 1 lần/ngày. Trẻ trên 12 tuổi và người lớn: Uống 1 viên/lần x 2 - 3 lần/ngày. Uống sau ăn.', '36 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng mặt trời trực tiếp. Để xa tầm tay trẻ em.', 'Không sử dụng cho người mẫn cảm với bất cứ thành phần nào của sản phẩm. Phụ nữ có thai, người đang dùng thuốc, điều trị bệnh tham khảo ý kiến bác sĩ trước khi dùng. Không dùng trong thời gian dài. Không dùng cho người tì vị hư yếu, đi đại tiện lỏng, ăn uống chậm tiêu.', '1714/2022/ĐKSP'),
(5, 'Viên uống Ericllux Ocavill hỗ trợ tăng tiết dịch khớp, giúp khớp vận động linh hoạt (60 viên)', 650000, 'https://github.com/Lizard943/webshop/blob/master/img/5.jpg?raw=true', 'Cơ xương khớp', 'Hộp 60 Viên', 'GRICAR', 'Ý', 'Glucosamin sulfat 2KCL, Methyl sulfonyl methan (MSM), Chondroitin sulfate, Nghệ, Bromelain 2500 GDU/g, Collagen thủy phân type 1, Calcium Carbonate, Vitamin D3, Vitamin K2 MK7, Kẽm (kẽm oxit), Vitamin B1', 'Ericllux hỗ trợ tăng tiết dịch khớp, giúp khớp vận động linh hoạt, giúp giảm các triệu chứng đau khớp, khô khớp do viêm khớp, thoái hóa khớp. Hỗ trợ giảm nguy cơ viêm khớp, thoái hóa khớp.', 'Ericllux thích hợp dùng cho người trưởng thành bị thoái hóa khớp, viêm khớp, khô khớp.', 'Uống 2 viên/ngày sau ăn.', '24 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng. Để xa tầm tay trẻ em.', 'Chưa có thông tin về tác dụng phụ của sản phẩm.', '6002/2022/ĐKSP'),
(6, 'Viên uống Calci Nano Hải Thượng Vương bổ sung Calci, vitamin D3 cho cơ thể (60 viên)', 347000, 'https://github.com/Lizard943/webshop/blob/master/img/6.jpg?raw=true', 'Cơ xương khớp', 'Hộp 60 Viên', 'CÔNG TY DƯỢC PHẨM VÀ THƯƠNG MẠI THÀNH CÔNG - TNHH', '\r\nViệt Nam', 'Calci carbonate nano, Aquamin F, Calci gluconat, Menaquinone MK7, Magie, Kẽm Gluconat, Vitamin D3, Đường Fructose - Oligosaccharide', 'Calci Nano Hải Thượng Vương bổ sung canxi, vitamin D3 cho cơ thể, giúp xương răng chắc khỏe, hỗ trợ cho trẻ em trong giai đoạn phát triển, giảm nguy cơ còi xương ở trẻ và loãng xương ở người lớn.', 'Calci nano Hải Thượng Vương dùng trong các trường hợp sau: Người lớn và trẻ em cần bổ sung canxi và vitamin D. Người lớn bị loãng xương, trẻ em bị còi xương, chậm mọc răng do thiếu vitamin D và canxi.', 'Người lớn và trẻ em trên 6 tuổi: Ngày uống 02 viên/lần. Nên uống vào buổi sáng hoặc buổi trưa và uống với nhiều nước để đạt được hiệu quả.', '3 năm kể từ ngày sản', 'Bảo quản nơi khô ráo, thoáng mát, tránh ánh sáng trực tiếp. Đậy nắp kỹ sau khi sử dụng. Để xa tầm tay trẻ em.', 'Không sử dụng cho người mẫn cảm với bất cứ thành phần nào của sản phẩm. Không dùng quá liều khuyến cáo. Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh.', '11156/2021/ĐKSP'),
(7, 'Viên uống Triple Strength Glucosamine 1500mg Pharmekal bổ sung dưỡng chất cho khớp (60 viên)', 296000, 'https://github.com/Lizard943/webshop/blob/master/img/7.jpg?raw=true', 'Cơ xương khớp', 'Hộp 60 Viên', 'NATURAL VITAMINS LABORATORY CROP', 'Hoa Kỳ', 'Glucosamine Hydrochloride, MSM, Collagen type I&III, Stearic acid, Magnesium stearate, Silicon Dioxyde, Croscamello Sodium, Chondroitin sulfate, Vitamin D3', 'Triple Strength Glucosamine bổ sung dưỡng chất cho khớp, hỗ trợ khớp vận động và linh hoạt.', 'Triple Strength Glucosamine dùng cho người trưởng thành vận động khớp khó khăn, khô khớp do thoái hóa khớp.', 'Uống 2 viên nén/ngày, có thể dùng với bữa ăn.', '24 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng. Để xa tầm tay trẻ em.', 'Không sử dụng cho người có mẫn cảm với bất kỳ thành phần nào của sản phẩm. Không dùng cho phụ nữ có thai, phụ nữ cho con bú, trẻ em, trẻ vị thành niên dưới 18 tuổi. Tham khảo ý kiến của chuyên gia trước khi uống nếu bạn đang dùng bất kỳ loại thuốc nào. Ngưng sử dụng nếu có bất kỳ phản ứng bất lợi nào xảy ra. Không dùng quá liều khuyến cáo. Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh. Đọc kỹ hướng dẫn sử dụng trước khi dùng.', '2814/2022/ĐKSP'),
(8, 'Siro Ginkid Ho Cam NEW 80ml hỗ trợ bổ phế, giảm ho, nhuận phế', 59000, 'https://github.com/Lizard943/webshop/blob/master/img/8.jpg?raw=true', '\r\nHô hấp, ho, xoang', 'Hộp x 80ml', 'ABIPHA', 'Việt Nam', 'Húng chanh, Mật ong, Thymomodulin, Xuyên bối mẫu, Trần bì, Kim ngân hoa, Tang bạch bì, Cát cánh, Bách bộ, Tỳ bà diệp', 'Ginkid Ho Cam hỗ trợ bổ phế, giảm ho, nhuận phế. Hỗ trợ giảm các triệu chứng: ho, cảm lạnh, hắt hơi, sổ mũi, ho do lạnh.', 'Ginkid Ho Cam dùng cho trẻ em từ 6 tháng tuổi trở lên trong các trường hợp sau: Trẻ em ho do lạnh, ho do dị ứng thời tiết, ho gió, ho khan, viêm họng, viêm phế quản, sưng đau rát họng, khàn tiếng. Trẻ bị cảm lạnh, hắt hơi, sổ mũi.', 'Trẻ em 6 tháng đến 1 tuổi: Uống 2,5ml/lần x 2 lần/ngày.\r\nTrẻ em từ 1 - 3 tuổi: Uống 5ml/lần x 2 lần/ngày.\r\nTrẻ em từ 3 - 6 tuổi: Uống 10ml/lần x 2 lần/ngày.\r\nTrẻ em từ 6 - 12 tuổi: Uống 10ml/lần x 2 - 3 lần/ngày.\r\nTrẻ em từ 12 tuổi trở lên: Uống 15ml/lần x 2 lần/ngày.', '18 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng.', 'Không sử dụng cho người mẫn cảm với bất cứ thành phần nào của sản phẩm. Không dùng quá liều khuyến cáo. Sản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh. Đọc kỹ hướng dẫn sử dụng trước khi dùng.', '7144/2018/ĐKSP'),
(9, 'Viên uống Lung Care+ Jpanwell hỗ trợ hệ hô hấp, giúp phổi khỏe mạnh (60 viên)', 995000, 'https://github.com/Lizard943/webshop/blob/master/img/9.jpg?raw=true', '\r\nHô hấp, ho, xoang', 'Hộp 60 Viên', 'GENSEI CO.,LTD', 'Nhật Bản', 'Bột hoa cúc tím', 'Lung Care+ hỗ trợ nâng cao sức khỏe, giúp tăng cường thể lực. Hỗ trợ hệ hô hấp khỏe mạnh.', 'Lung Care+ thích hợp cho người trưởng thành trong các trường hợp: Cần tăng cường thể lực, nâng cao sức khỏe. Cần hỗ trợ hệ hô hấp khỏe mạnh.', 'Uống 2 viên/ngày với nước nguội hoặc nước ấm.', '2 năm từ ngày sản xu', 'Bảo quản nơi khô ráo, thoáng mát, tránh ánh sáng trực tiếp. Để xa tầm tay của trẻ em.', 'Cân bằng chế độ dinh dưỡng giữa các bữa chính, bữa phụ. Nếu bạn bị dị ứng thực phẩm, vui lòng đọc kỹ các thành phần trước khi sử dụng. Ngưng sử dụng sản phẩm khi có bất cứ dấu hiệu bất lợi nào với cơ thể. Sản phẩm này có chứa các nguyên liệu có nguồn gốc tự nhiên, nên màu sắc hương vị tổng hợp có thể hơi khác nhưng không ảnh hưởng đến chất lượng của sản phẩm.', '3408/2022/ĐKSP'),
(10, 'Xịt họng Xuyên Tâm Liên Hải Thượng Vương hỗ trợ giảm ho, giảm đờm, giảm đau rát họng, khàn tiếng (30ml)', 106000, 'https://github.com/Lizard943/webshop/blob/master/img/10.jpg?raw=true', 'Hô hấp, ho, xoang', 'Hộp', 'VESTA', 'Việt Nam', 'Keo Ong, Cao lá thường xuân, Xuyên tâm liên, Chiết xuất cúc la mã, dịch chiết quả sơ ri, Tinh dầu bạc hà, chiết xuất cúc tím', 'Xuyên Tâm Liên Hải Thượng Vương hỗ trợ giảm ho, giảm đờm, giảm đau rát họng, khản tiếng do viêm họng, viêm phế quản.', 'Xuyên Tâm Liên Hải Thượng Vương thích hợp dùng cho trẻ từ 3 tuổi và người lớn bị ho, ho có đờm do viêm họng, viêm phế quản.', 'Mỗi nhịp xịt khoảng 0,2ml. Trẻ từ 3 tuổi đến 12 tuổi: Ngày xịt 2 lần, mỗi lần 2 - 3 nhịp (tương đương 0,8ml - 1,2 ml/ngày). Trẻ trên 12 tuổi và người lớn: Ngày xịt 2 lần, mỗi lần 3 - 4 nhịp (tương đương 1,2ml - 1,6ml/ngày', '24 tháng kể từ ngày ', 'Bảo quản nơi khô ráo, thoáng mát, nhiệt độ không quá 30 độ C, tránh ánh sáng. Để xa tầm tay trẻ em.', 'Không dùng trong thời gian dài ảnh hưởng tới đường tiêu hóa. Không dùng Xuyên Tâm Liên Hải Thượng Vương cho các trường hợp sau: Người bị tiêu chảy. Trẻ có tiền sử động kinh, co giật, sốt cao. Người mẫn cảm với bất cứ thành phần nào của sản phẩm. Người đang sử dụng thuốc điều trị bệnh, phụ nữ mang thai tham khảo ý kiến chuyên gia y tế trước khi sử dụng. Không dùng quá liều khuyến cáo.\r\nSản phẩm này không phải là thuốc và không có tác dụng thay thế thuốc chữa bệnh. Đọc kỹ hướng dẫn sử dụng trước khi dùng.', '1397/2022/ĐKSP');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
